### ISSUE TITLE
phosphor-dbus-monitor doesn't support double values

### ISSUE THREAD

**Issue by wvervoorn** [openbmc/phosphor-dbus-monitor#4]
The PDM doesn't support double values on the D-Bus this is causing problems when used with dbus-sensors. Just added two pull requests to solve this issue.

Verified this on a test system and it is working.

**Comment by matthewfischer** [comment]
I am assuming these merged in the last 5 years -can we close the issue?

**Comment by williamspatrick** [comment]
Yes.  Equivalent code appears to already be merged.

@wvervoorn For the future (even though this was now 5 years ago) we don't take PRs for the project but only use Gerrit to take contributions.
